# Autogenerated by devscripts/update-version.py

__version__ = '2024.01.06.061913'

RELEASE_GIT_HEAD = '9915f10ea1ea5a58be6b78410a9f22201f69a3d1'

VARIANT = None

UPDATE_HINT = None

CHANNEL = 'qjao/yt-dlp'

ORIGIN = 'qjao/yt-dlp'

_pkg_version = '2024.01.06.061913'
